spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: li6193818
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

    #    pathmatch:
#      matching:
#        stategy: ant path matcher
#    static-path-pattern: /javablog/**


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8080




